# Generated by Django 4.0.6 on 2022-07-06 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilechatdetails',
            name='profile',
        ),
        migrations.AddField(
            model_name='profilechatdetails',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.profile'),
            preserve_default=False,
        ),
    ]
