# Generated by Django 4.0.5 on 2022-07-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
