# Generated by Django 4.0.6 on 2022-07-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, default='', related_name='read_by', to='chat.person'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
