# Generated by Django 4.0.6 on 2022-07-05 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_message_read_by_alter_chat_chat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], default='M', max_length=1)),
                ('country', models.CharField(max_length=127)),
                ('date_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileChatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time_active_on_chat', models.DateTimeField(auto_now=True)),
                ('chat_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('profile', models.ManyToManyField(to='chat.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='message',
            name='person',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='chat',
            name='profile_chat_details_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chat.profilechatdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chat.profile'),
            preserve_default=False,
        ),
    ]
