# Generated by Django 4.0.6 on 2022-07-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_profile_profilechatdetails_remove_chat_chat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='profile_chat_details_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.profilechatdetails'),
        ),
    ]
