# Generated by Django 4.0.6 on 2022-07-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_profile_chat_details_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechatdetails',
            name='profile',
            field=models.ManyToManyField(null=True, to='chat.profile'),
        ),
    ]
