# Generated by Django 4.0.6 on 2022-07-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_profilechatdetails_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='profile_chat_details_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.profilechatdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilechatdetails',
            name='profile',
            field=models.ManyToManyField(to='chat.profile'),
        ),
    ]
